# streamlit_app/labels.py
from typing import Dict

# --- Constants ---
LABELS: Dict[str, Dict[str, str]] = {
    'en': {
        "page_title": "Churn Prediction App",
        "title": "Customer Data",
        'Age': 'Age',
        'Balance': 'Balance',
        'Credit Score': 'Credit Score',
        'Gender': 'Gender',
        'Active Member': 'Active Member',
        'Geography': 'Geography',
        'Number of Products': 'Number of Products',
        'Submit': 'Predict Churn',
        'Prediction': 'Prediction',
        'Churn Prediction': 'Customer Churn Prediction',
        'Input Features': 'Input Features',
        'Result': 'Result',
        'Churn Message': "The customer is likely to leave the bank.",
        'Stay Message': "The customer is likely to stay with the bank.",
        'Churn Recommendation': "We recommend reaching out with exclusive offers or enhanced services to retain the customer.",
        'Stay Recommendation': "Consider offering additional products or benefits to further increase loyalty.",
        'Probability': 'Probability',
        'Feature Importance Title': 'Prediction Explanation (SHAP)',
        'Feature Importance Info': 'Install SHAP (`pip install shap matplotlib`) to see prediction explanations.',
        'SHAP Error': 'Could not calculate or display SHAP explanation.',
        'Show Input Data': 'Show Prediction Input Data',
        'Model Error': 'Error loading model file.',
        'Prediction Error': 'An error occurred during prediction.',
        'Proba Error': 'Model does not support probability prediction. Showing basic prediction.',
        'Select Language': 'Select Language / اختر اللغة',
        'Account Details': 'Account Details',
        'Predicting': 'Predicting...',
        'Preset Label': 'Load Example Profile',
        'Preset Custom': '-- Select Custom Input --',
        'Preset High Risk': 'Example: High Risk Customer',
        'Preset Loyal': 'Example: Loyal Customer',
        # Tooltips
        'Age Help': 'Enter customer age (18-100)',
        'Balance Help': 'Enter customer account balance',
        'Credit Score Help': 'Enter customer credit score (300-850)',
        'Gender Help': 'Select customer gender',
        'Active Member Help': 'Is the customer an active member?',
        'Geography Help': 'Select customer\'s country',
        'Num Products Help': 'Number of bank products the customer uses (1-4)',
    },
    'ar': {
        "page_title": "تطبيق توقع المغادرة",
        "title": " بيانات العميل",
        'Age': 'العمر',
        'Balance': 'الرصيد',
        'Credit Score': 'درجة الائتمان',
        'Gender': 'الجنس',
        'Active Member': 'عضو نشط',
        'Geography': 'المنطقة',
        'Number of Products': 'عدد المنتجات',
        'Submit': 'توقع المغادرة',
        'Prediction': 'التنبؤ',
        'Churn Prediction': 'تنبؤ مغادرة العميل',
        'Input Features': 'معلومات الإدخال',
        'Result': 'النتيجة',
        'Churn Message': "من المرجح أن يغادر العميل البنك.",
        'Stay Message': "من المرجح أن يظل العميل في البنك.",
        'Churn Recommendation': "نوصي بالتواصل مع العميل وتقديم عروض حصرية أو تحسينات في الخدمة.",
        'Stay Recommendation': "يمكن تقديم عروض إضافية أو منتجات مالية لتعزيز ولاء العميل.",
        'Probability': 'الاحتمالية',
        'Feature Importance Title': 'تفسير التنبؤ (SHAP)',
        'Feature Importance Info': 'قم بتثبيت SHAP (`pip install shap matplotlib`) لعرض تفسيرات التنبؤ.',
        'SHAP Error': 'تعذر حساب أو عرض تفسير SHAP.',
        'Show Input Data': 'عرض بيانات الإدخال للتنبؤ',
        'Model Error': 'خطأ في تحميل ملف النموذج.',
        'Prediction Error': 'حدث خطأ أثناء التنبؤ.',
        'Proba Error': 'النموذج لا يدعم التنبؤ بالاحتمالات. عرض التنبؤ الأساسي.',
        'Select Language': 'Select Language / اختر اللغة',
        'Account Details': 'تفاصيل الحساب',
        'Predicting': 'جاري التنبؤ...',
        'Preset Label': 'تحميل ملف تعريف مثال',
        'Preset Custom': '-- تحديد إدخال مخصص --',
        'Preset High Risk': 'مثال: عميل عالي المخاطر',
        'Preset Loyal': 'مثال: عميل وفي',
        # Tooltips (Arabic)
        'Age Help': 'أدخل عمر العميل (18-100)',
        'Balance Help': 'أدخل رصيد حساب العميل',
        'Credit Score Help': 'أدخل درجة الائتمان للعميل (300-850)',
        'Gender Help': 'اختر جنس العميل',
        'Active Member Help': 'هل العميل عضو نشط؟',
        'Geography Help': 'اختر بلد العميل',
        'Num Products Help': 'عدد المنتجات البنكية التي يستخدمها العميل (1-4)',
    }
}